swagger: '2.0'
info:
  description: API para el manejo de apuestas
  version: "1.0.1"
  title: Apuestas API
  # put the contact info for your development or API team
  contact:
    email: vin001@gmail.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: administradores
  description: Opciones para administrar
- name: apostadores
  description: Operaciones para apostadores

paths:
  /torneo/{idTorneo}:
    get:
      tags:
      - administradores
      - apostadores
      summary: busca un torneo
      operationId: buscarTorneo
      description: |
        Encviando un ID valido devuelve la informacion del torneo
      consumes: 
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: idTorneo
        description: id del torneo a buscar
        required: true
        type: string
      responses:
        200:
          description: devuelve el resultado obtenido
          schema:
            type: object
            items:
              $ref: '#/definitions/Torneo'
        400:
          description: mal entrada de datos
    post:
      tags:
      - adminstradores
      summary: Creación de torneos de fútbol
      operationId: agregarTorneo
      description: Crear un torneo de fútbol
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: idTorneo
        description: id del torneo a buscar
        required: true
        type: string
      - in: body
        name: torneo
        description: Torneo a agregar
        schema:
          $ref: '#/definitions/Torneo'
      responses:
        201:
          description: torneo creado
        400:
          description: objeto no válido
        409:
          description: an existing item already exists
  /cotejo/{idCotejo}:
    get:
      tags:
      - administradores
      - apostadores
      summary: busca un cotejo
      operationId: buscarCotejo
      description: |
        Encviando un ID valido devuelve la informacion del cotejo
      produces:
      - application/json
      parameters:
      - in: path
        name: idCotejo
        description: id del cotejo a buscar
        required: true
        type: string
      responses:
        200:
          description: devuelve el resultado obtenido
          schema:
            type: object
            items:
              $ref: '#/definitions/Cotejo'
        400:
          description: mal entrada de datos
    post:
      tags:
      - adminstradores
      summary: Creación de cotejos de fútbol
      operationId: agregarCotejo
      description: Crear un torneo de fútbol
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: idCotejo
        description: id del cotejo a buscar
        required: true
        type: string
      - in: body
        name: cotejo
        description: Cotejo a agregar
        schema:
          $ref: '#/definitions/Cotejo'
      responses:
        201:
          description: cotejo creado
        400:
          description: objeto no válido
        409:
          description: el cotejo ya existe          
  /apuesta/{idApuesta}:
    get:
      tags:
      - apostadores
      summary: busca una apuesta
      operationId: buscarApuesta
      description: |
        Encviando un ID valido devuelve la informacion de la apuesta
      produces:
      - application/json
      parameters:
      - in: path
        name: idApuesta
        description: id de la apuesta a buscar
        required: true
        type: string
      responses:
        200:
          description: devuelve el resultado obtenido
          schema:
            type: object
            items:
              $ref: '#/definitions/Apuesta'
        400:
          description: mal entrada de datos
    post:
      tags:
      - adminstradores
      summary: Creación de apuestas de fútbol
      operationId: agregarApuesta
      description: Crear una apuesta de un torneo de fútbol
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: idApuesta
        description: id de la apuesta a buscar
        required: true
        type: string
      - in: body
        name: cotejo
        description: Apuesta a agregar
        schema:
          $ref: '#/definitions/Apuesta'
      responses:
        201:
          description: apuesta creada
        400:
          description: objeto no válido
        409:
          description: la apuesta ya existe          
definitions:
  Torneo:
    type: object
    required:
    - idTorneo
    - nombre
    - fechaTorneo
    properties:
      idTorneo:
        type: string
        example: t123
      nombre:
        type: string
        example: Rusia 2018
      fechaTorneo:
        type: string
        format: int32
        example: 2016-08-29T09:12:33.001Z
  Cotejo:
    type: object
    required: 
    - idCotejo
    - nombre
    - equipo1
    - equipo2
    - idTorneo
    properties:
      idCotejo:
        type: string
        example: c123
      nombre:
        type: string
        example: semifinal
      equipo1:
        type: string
        example: Croacia        
      equipo2:
        type: string
        example: Colombia
      idTorneo:
        type: string
        example: t123
  Apuesta:
    type: object
    required:
    - idApuesta
    - idCotejo
    - valor
    properties:
      idApuesta:
        type: string
        example: a123
      idCotejo:
        type: string
        example: c123
      valor:
        type: integer
        example: 10
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /vin001gmailcom/ApuestasAPI/1.0.0
schemes:
 - https